### ISSUE TITLE
What's with this repo?

### ISSUE THREAD

**Issue by wh4everest** [hfour/yads#10]
I see we have yads and yads-archive, I don't get it?

**Comment by spion** [comment]
The repo is broken for some reason, github is failing to retreive commits, pull requests and pushes often  get stuck.

I tried to move the old one to yads-archive but we're still getting the same issues in the new one too. Looks like we might need to start with a clean history, as the current one may be corrupt.

**Comment by spion** [comment]
Now it seems like the repo has recovered. Its as if it ended up in some failing storage cluster initially and now it has moved to a working one. Strange.

I've renamed the repo back; hopefully the problem won't repeat itself. If it does I think we should probably contact GH support
